import bcrypt from 'bcryptjs';

export default async () => {
  return [
    {
      email: 'michael@email.com',
      name: 'Michael Scott',
      role: 'admin',
      __t: 'admin',
      password: bcrypt.hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
    },
    {
      email: 'jim@email.com',
      name: 'Jim Halpert',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      xp: 1500,
    },
    {
      email: 'pam@email.com',
      name: 'Pam Beesly',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: true,
      confirmed: false,
      xp: 1500,
    },
    {
      email: 'dwight@email.com',
      name: 'Dwight Schrute',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      xp: 2200,
    },
    {
      email: 'angela@email.com',
      name: 'Angela Martin',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: false,
      confirmed: true,
      xp: 1800,
    },
    {
      email: 'kevin@email.com',
      name: 'Kevin Malone',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      xp: 900,
    },
    {
      email: 'oscar@email.com',
      name: 'Oscar Martinez',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      xp: 1650,
    },
    {
      email: 'stanley@email.com',
      name: 'Stanley Hudson',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: true,
      confirmed: false,
      xp: 1300,
    },
    {
      email: 'kelly@email.com',
      name: 'Kelly Kapoor',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      xp: 1100,
    },
    {
      email: 'toby@email.com',
      name: 'Toby Flenderson',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: false,
      confirmed: true,
      xp: 800,
    },
    {
      email: 'andy@email.com',
      name: 'Andy Bernard',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      xp: 1250,
    },
    {
      email: 'phyllis@email.com',
      name: 'Phyllis Vance',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: true,
      confirmed: true,
      xp: 1400,
    },
    {
      email: 'creed@email.com',
      name: 'Creed Bratton',
      role: 'client',
      __t: 'client',
      password: bcrypt.hashSync('supersecretpassword'),
      active: true,
      confirmed: false,
      xp: 750,
    },
  ];
};
